### PR TITLE
make the enchantments extractor 1.15.2 compatible

### PR DESCRIPTION
**Pull request by uncovery**
This outputs an array with all current enchantments in the format of :

```
 { displayName: 'Sharpness',
    maxLevel: '5',
    primaries: [ 'Diamond Sword' ],
    secondaries: [ 'Diamond Axe' ],
    excludes: [ 'Bane of Arthropods', 'Smite' ],
    probability: 10 },
```

Currently only supports displaynames for items and enchantments. would need to be cross-referenced with another list to get itemnames and enchantmentnames.

### CODE REVIEW

**Comment by uncovery** [comment]
Please note that this is not complete yet working together with the _to_json... function

**Comment by uncovery** [comment]
This of course only works with somewhat recent versions

**Comment by uncovery** [comment]
I wonder if it makes sense to have a different code depending on the version to maintain backwards compatibility.

**Comment by uncovery** [comment]
Hey guys, I don't want to rush you in any way (seriously) but given the discussions in other issues if the wiki-extractor is still needed at all, I was wondering if it's a time issue that this is not merged or a principle issue?  If there is a chance that this will not see the sunlight, I rather just go ahead and re-write this in PHP so that it works directly in my website instead of trying to add wiki content from here.

Thanks so much for the work on these projects!

**Comment by uncovery** [comment]
New export format is now:

```
 {
    "itemName": "minecraft.blast_protection",
    "displayName": "Blast Protection",
    "maxLevel": 5,
    "primaries": [
      "minecraft.diamond_helmet",
      "minecraft.diamond_chestplate",
      "minecraft.diamond_leggings",
      "minecraft.diamond_boots",
      "minecraft.turtle_helmet"
    ],
    "secondaries": [],
    "excludes": [
      "minecraft.fire_protection",
      "minecraft.projectile_protection",
      "minecraft.protection"
    ],
    "probability": 2
  },

```

it reads the language.json from the mincraft-data folder to translate the display names to itemNames for enchantments and items. This requires that when calling the function to use the path including the verison name, such as 

`node ./bin/enchantments_to_json.js ./../minecraft-data/data/pc/1.15.2/ 2020-05-11T00:00:00Z`

this results also in the positive effect that it will sort out enchantments and items in the Wiki that do not exist in the given version. this will be displayed as such:

```
NOTICE: could not find Chopping enchantment in language file! Wiki item is likely for next version.
NOTICE: could not find Warped Fungus on a Stick item in language file! Wiki item is likely for next version.
NOTICE: could not find Soul Speed enchantment in language file! Wiki item is likely for next version.
```

**Comment by rom1504** [comment]
Looks ok to me, if you think it's ready to merge, we can merge it.
About the version compatibility : it doesn't matter too much. The wiki is too brittle to maintain something that would work for all version.
If we want to extract again an older version, the best way is simply to go back to the commit that could do that.

Is this ready to merge ? Can you open a PR on minecraft data with the data ?

(And could you quickly check if this could work for 1.13 and 1.14, I think we have incorrect data for those ?)

**Comment by uncovery** [comment]
ok let me open a PR with the data first so you can take a look at it

**Comment by uncovery** [comment]
FYI this works with 1.14.4 but not with 1.13.2

**Comment by uncovery** [comment]
above commits fix an error (./:) and prepare changes for the new schema (itemName/name)

**Comment by rom1504** [comment]
should we merge this ?

**Pull request closed without merging**
